baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Stanford Waterworks"

[params]
    Id = "stanfordwater"
    Color = "#558ed5"
    AppTitle = "SWW Advisory"
    Description = "Alerts and interactive map to serve the customers of Stanford Waterworks"
    Facebook = ""
    BillPay = "https://stanfordwater.epayub.com"

[blackfriday]
    extensions = ["hardLineBreak"]

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
